version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/produits-deb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_SECURITY_USER_NAME: oth
      SPRING_SECURITY_USER_PASSWORD: 1300

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: produits-deb
    ports:
      - "3307:3306"
